name: mgm_ops_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0



  # flutter_lints: ^6.0.0


flutter:

  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0b1b4d"
  adaptive_icon_foreground: "assets/icon/app_icon.png"