// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBQbG5qsScwoU4oepftb6i5uU_a05jAw_w',
//     appId: '1:825981197461:web:f108a721c1bc79969bcf9c',
//     messagingSenderId: '825981197461',
//     projectId: 'mgm-hotel-ops',
//     authDomain: 'mgm-hotel-ops.firebaseapp.com',
//     storageBucket: 'mgm-hotel-ops.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCaRYUQN9lHHL8KehtdSlsK4zNC6gu6lrg',
//     appId: '1:825981197461:android:541055a91410f2869bcf9c',
//     messagingSenderId: '825981197461',
//     projectId: 'mgm-hotel-ops',
//     storageBucket: 'mgm-hotel-ops.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDnP3K4Bsj3VohGtaK8jLoSwQFzdlHwCc8',
//     appId: '1:825981197461:ios:7586e50ed8bf76299bcf9c',
//     messagingSenderId: '825981197461',
//     projectId: 'mgm-hotel-ops',
//     storageBucket: 'mgm-hotel-ops.firebasestorage.app',
//     iosBundleId: 'com.example.mgmOpsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDnP3K4Bsj3VohGtaK8jLoSwQFzdlHwCc8',
//     appId: '1:825981197461:ios:7586e50ed8bf76299bcf9c',
//     messagingSenderId: '825981197461',
//     projectId: 'mgm-hotel-ops',
//     storageBucket: 'mgm-hotel-ops.firebasestorage.app',
//     iosBundleId: 'com.example.mgmOpsApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBQbG5qsScwoU4oepftb6i5uU_a05jAw_w',
//     appId: '1:825981197461:web:562edc6be7b749289bcf9c',
//     messagingSenderId: '825981197461',
//     projectId: 'mgm-hotel-ops',
//     authDomain: 'mgm-hotel-ops.firebaseapp.com',
//     storageBucket: 'mgm-hotel-ops.firebasestorage.app',
//   );
// }
